name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  parallax: ^1.0.3
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.0
  get_it: ^7.6.0
  shake: ^2.2.0
  flutter_tts: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true
  assets:
    - assets/images/
